volumes: # データを永続保存するためにdocker volumeを設定
  redis-volume:

services:
  # phpの設定
  app: # サービス名（≠コンテナ名）を指定
    container_name: fib-app # コンテナ名を指定（別のdocker環境がある場合、そちらとコンテナ名が被らないように注意）
    build: # ビルドするDockerfileの設定
      context: . # docker buildコマンドを実行する場所を指定（基本ルートディレクトリを指定しておけば良い（*2））
      dockerfile: ./docker/php/Dockerfile # Dockerfileがあるパスを指定
    volumes: # ローカルとdockerコンテナ間のディレクトリやファイルなどのリソースを対応付け
      - ./src:/var/www/html # {ローカルのリソースのパス}:{dockerコンテナのリソースのパス}

  # nginxの設定
  web:
    container_name: fib-nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports: # ローカルとdockerコンテナ間のポート番号の対応付けを設定
      - ${WEB_PORT}:80 # {ローカルのポート番号}:{dockerコンテナのポート番号}（ローカルは未使用のポートを指定すること、dockerはかぶっていてもOK）
    depends_on: # コンテナ間の依存関係を設定
      - app # 先に起動するコンテナのサービス名を指定（コンテナ名ではない）
    volumes:
      - ./src:/var/www/html

  redis:
    container_name: fib-redis
    image: redis:7.2-alpine
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-volume:/var/lib/redis
